# Params for Simple_RNN

$params = cell\times input\_size + cell^2$

$cell^2$ means cells are fullly connected to themselves   meaning?


In [0]:
# colab.research.google.com
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import *
import numpy as np

'''
# labs.cognitiveclass.ai
import keras
from keras.layers import *
import numpy as np
'''

In [2]:
cell = 1
input_size = 2
time_steps = 1    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [3]:
model.get_weights()

[array([[ 1.3357459],
        [-0.429412 ]], dtype=float32), array([[-1.]], dtype=float32)]

In [0]:
model.set_weights([[[2],[3]],[[5]]])

In [5]:
x = np.array([1, 0])
x = x.reshape(1,1,2)
model.predict(x)

array([[2.]], dtype=float32)

# 2 timesteps

In [6]:
cell = 1
input_size = 2
time_steps = 2    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.set_weights([[[2],[3]],[[5]]])

In [8]:
x = np.array([1, 0, 0, 0])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [0 0]]]


array([[10.]], dtype=float32)

In [9]:
x = np.array([1, 0, 1, 0])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [1 0]]]


array([[12.]], dtype=float32)

In [10]:
x = np.array([1, 0, 0, 1])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [0 1]]]


array([[13.]], dtype=float32)

# 3 timesteps

In [11]:
cell = 1
input_size = 2
time_steps = 3    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.set_weights([[[2],[3]],[[5]]])

In [13]:
x = np.array([1, 0, 0, 1, 7, 11])
x = x.reshape(1,3,2)
print(x)
model.predict(x) == 2 * 7 + 3 * 11 + 5 * 13

[[[ 1  0]
  [ 0  1]
  [ 7 11]]]


array([[ True]])

# Add another example

In [14]:
x = np.array([1, 0, 0, 1, 7, 11, 1, 0, 0, 1, 7, 11])
x = x.reshape(2,3,2)
print(x)
model.predict(x) == 2 * 7 + 3 * 11 + 5 * 13

[[[ 1  0]
  [ 0  1]
  [ 7 11]]

 [[ 1  0]
  [ 0  1]
  [ 7 11]]]


array([[ True],
       [ True]])

# Prepare Training Data

In [15]:
def get_bit(n, bit):
    a = []
    for i in range(bit):
        a.append(n & 1)
        n >>= 1
    return a
  
for i in range(3):
    print(get_bit(i, 8))

[0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0]


In [0]:
time_steps = 8

x = []
y = []
for i in range(2**time_steps):
    for j in range(2**time_steps):
        i_b = get_bit(i, time_steps)
        j_b = get_bit(j, time_steps)
        x.append([[i_b[i], j_b[i]] for i in range(time_steps)])
        y.append([get_bit(i+j, 8)[-1]])
    

In [17]:
i = 256*128#256*11 + 5 # 256*3 + 5
print(x[i])
print(y[i])

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0]]
[1]


In [0]:
#for i in range(len(x)):
#  print(x[i], y[i])

In [19]:
import numpy as np

x = np.array(x)
x.shape

(65536, 8, 2)

In [20]:
y = np.array(y)
y.shape

(65536, 1)

# Train

In [21]:
cell = 8
input_size = 2
time_steps = 8    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #LSTM(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        Dense(1, activation='relu', use_bias=False)    
])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (None, 8)                 80        
_________________________________________________________________
dense (Dense)                (None, 1)                 8         
Total params: 88
Trainable params: 88
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam', # tf.keras.optimizers.SGD(lr=0.01),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [23]:
model.fit(x, y, epochs=10)    # training in colab is 4x faster than my PC!?!

Epoch 1/10
65536/65536 [==============================] - 4s 62us/step - loss: 1.3914 - acc: 0.4340
Epoch 2/10
65536/65536 [==============================] - 4s 55us/step - loss: 0.7431 - acc: 0.4791
Epoch 3/10
65536/65536 [==============================] - 4s 55us/step - loss: 0.5767 - acc: 0.6282
Epoch 4/10
65536/65536 [==============================] - 4s 55us/step - loss: 0.3704 - acc: 0.8617
Epoch 5/10
65536/65536 [==============================] - 4s 55us/step - loss: 0.0745 - acc: 0.9845
Epoch 6/10
65536/65536 [==============================] - 4s 54us/step - loss: 0.0027 - acc: 1.0000
Epoch 7/10
65536/65536 [==============================] - 4s 55us/step - loss: 1.3837e-04 - acc: 1.0000
Epoch 8/10
65536/65536 [==============================] - 4s 56us/step - loss: 3.3025e-05 - acc: 1.0000
Epoch 9/10
65536/65536 [==============================] - 4s 56us/step - loss: 3.7986e-05 - acc: 1.0000
Epoch 10/10
65536/65536 [==============================] - 4s 55us/step - loss: 8.7531e-

In [24]:
a = model.predict_classes(x)
all(a == y)

True

In [0]:
def add(a, b):
  bit = max(a.bit_length(), b.bit_length()) + 1

  a = get_bit(a, bit)
  b = get_bit(b, bit)
  c = [[0,0] for i in range(7)]
  
  result = []
  for i in range(bit):
    c.append([a[i], b[i]])
    x = np.array(c)
    x = x.reshape(1,8,2)
    y = model.predict_classes(x)[0][0]
    result.append(y)
    c = c[1:]
    assert y == 0 or y == 1, y
    assert len(c) == 7

  r = 0
  for i in reversed(result):
    r <<= 1
    r += int(i)
  return r

In [33]:
print(add(0,0))
print(add(0,1))
print(add(1,0))
print(add(1,1))
print(add(1234567812345678,8765432187654321))

0
1
1
2
9999999999999999


In [34]:
import random

# there are some errors due to no carry bit
for i in range(10):
  a = random.getrandbits(128)
  b = random.getrandbits(128)
  r = add(a, b)
  if r != a + b:
    print('x', a, b, r)
  else:
    print('o', a, b, r)

o 259282831300135068981371319005529531294 79504777755290544244469175521251298585 338787609055425613225840494526780829879
x 197988367563467979405760615468320721522 73924822643355974019059526480379902351 271913190206823953424820141948700623361
o 56113787733831585266392060346988265062 24156440481792064250946725018471923852 80270228215623649517338785365460188914
o 127052996698209027309732136654439786246 324111033920428099453743665024420148424 451164030618637126763475801678859934670
x 40108008484855863954290620318384311039 187672941798042752541814643606179255031 227780950282898616496105263924496457206
o 242390294915243331110714829992880596314 207487034073301027568580120715521099664 449877328988544358679294950708401695978
x 149959977286226242532151911385338078847 43492134506682605816109317854000521586 193452101651704046522426017265712957425
o 265451000625497420634163825293557595459 67760954602212774012330608484730954367 333211955227710194646494433778288549826
o 209527009907326260553662467706