# Params for Simple_RNN

$params = cell\times input\_size + cell^2$

$cell^2$ means cells are fullly connected to themselves   meaning?


In [0]:
%tensorflow_version 1.x

In [2]:
# colab.research.google.com
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import *
import numpy as np

'''
# labs.cognitiveclass.ai
import keras
from keras.layers import *
import numpy as np
'''

'\n# labs.cognitiveclass.ai\nimport keras\nfrom keras.layers import *\nimport numpy as np\n'

# 1 timestep

In [3]:
cell = 1
input_size = 2
time_steps = 1    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.get_weights()

[array([[-0.3636521],
        [ 1.3807131]], dtype=float32), array([[-1.]], dtype=float32)]

In [0]:
def to_npa_list(a):
  return [np.array(i) for i in a]

model.set_weights(to_npa_list([[[2],[3]],[[5]]]))

In [6]:
x = np.array([1, 0])
x = x.reshape(1,1,2)
model.predict(x)

array([[2.]], dtype=float32)

# 2 timesteps

In [7]:
cell = 1
input_size = 2
time_steps = 2    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.set_weights(to_npa_list([[[2],[3]],[[5]]]))

In [9]:
x = np.array([1, 0, 0, 0])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [0 0]]]


array([[10.]], dtype=float32)

In [10]:
x = np.array([1, 0, 1, 0])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [1 0]]]


array([[12.]], dtype=float32)

In [11]:
x = np.array([1, 0, 0, 1])
x = x.reshape(1,2,2)
print(x)
model.predict(x)

[[[1 0]
  [0 1]]]


array([[13.]], dtype=float32)

# 3 timesteps

In [12]:
cell = 1
input_size = 2
time_steps = 3    

model = keras.Sequential([
        SimpleRNN(cell, activation='relu', use_bias=False, input_shape=(time_steps, input_size)),
        #Dense(1, activation='relu', use_bias=False)    
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.set_weights(to_npa_list([[[2],[3]],[[5]]]))

In [14]:
x = np.array([1, 0, 0, 1, 7, 11])
x = x.reshape(1,3,2)
print(x)
model.predict(x) == 2 * 7 + 3 * 11 + 5 * 13

[[[ 1  0]
  [ 0  1]
  [ 7 11]]]


array([[ True]])