In [49]:
import pandas as pd

df = pd.read_csv('weather.nominal.csv')
df

outlook temperature humidity  windy play
0      sunny        cool   normal  False  yes
1      sunny        mild   normal   True  yes
2      sunny         hot     high  False   no
3      sunny         hot     high   True   no
4      sunny        mild     high  False   no
5      rainy        mild     high  False  yes
6      rainy        cool   normal  False  yes
7      rainy        mild   normal  False  yes
8      rainy        cool   normal   True   no
9      rainy        mild     high   True   no
10  overcast         hot     high  False  yes
11  overcast        cool   normal   True  yes
12  overcast        mild     high   True  yes
13  overcast         hot   normal  False  yes

In [50]:
df.describe(include='all')

outlook temperature humidity  windy play
count       14          14       14     14   14
unique       3           3        2      2    2
top      sunny        mild   normal  False  yes
freq         5           6        7      8    9

In [51]:
df.play.value_counts()

yes    9
no     5
Name: play, dtype: int64

In [52]:
dfy = df[df.play == 'yes']
dfn = df[df.play == 'no']

In [53]:
for c in dfy.columns:
    print(dfy[c].value_counts())
    print('-' * 30)

overcast    4
rainy       3
sunny       2
Name: outlook, dtype: int64
------------------------------
mild    4
cool    3
hot     2
Name: temperature, dtype: int64
------------------------------
normal    6
high      3
Name: humidity, dtype: int64
------------------------------
False    6
True     3
Name: windy, dtype: int64
------------------------------
yes    9
Name: play, dtype: int64
------------------------------


In [54]:
for c in dfn.columns:
    print(dfn[c].value_counts())
    print('-' * 30)

sunny    3
rainy    2
Name: outlook, dtype: int64
------------------------------
mild    2
hot     2
cool    1
Name: temperature, dtype: int64
------------------------------
high      4
normal    1
Name: humidity, dtype: int64
------------------------------
True     3
False    2
Name: windy, dtype: int64
------------------------------
no    5
Name: play, dtype: int64
------------------------------


# Smoothing

In [55]:
df = df.iloc[:12]
df

outlook temperature humidity  windy play
0      sunny        cool   normal  False  yes
1      sunny        mild   normal   True  yes
2      sunny         hot     high  False   no
3      sunny         hot     high   True   no
4      sunny        mild     high  False   no
5      rainy        mild     high  False  yes
6      rainy        cool   normal  False  yes
7      rainy        mild   normal  False  yes
8      rainy        cool   normal   True   no
9      rainy        mild     high   True   no
10  overcast         hot     high  False  yes
11  overcast        cool   normal   True  yes

In [56]:
dfy = df[df.play == 'yes']
dfn = df[df.play == 'no']

In [57]:
for c in dfy.columns:
    print(dfy[c].value_counts())
    print('-' * 30)

rainy       3
overcast    2
sunny       2
Name: outlook, dtype: int64
------------------------------
cool    3
mild    3
hot     1
Name: temperature, dtype: int64
------------------------------
normal    5
high      2
Name: humidity, dtype: int64
------------------------------
False    5
True     2
Name: windy, dtype: int64
------------------------------
yes    7
Name: play, dtype: int64
------------------------------


In [58]:
for c in dfn.columns:
    print(dfn[c].value_counts())
    print('-' * 30)

sunny    3
rainy    2
Name: outlook, dtype: int64
------------------------------
mild    2
hot     2
cool    1
Name: temperature, dtype: int64
------------------------------
high      4
normal    1
Name: humidity, dtype: int64
------------------------------
True     3
False    2
Name: windy, dtype: int64
------------------------------
no    5
Name: play, dtype: int64
------------------------------


In [74]:
s = df.outlook.value_counts()
s[:] = 1
s
s = dfn.outlook.value_counts() + s
s.fillna(1, inplace=True)
s.astype('int64')

overcast    1
rainy       3
sunny       4
Name: outlook, dtype: int64

In [78]:
def smooth(df, dff, c):
    s = df[c].value_counts()
    s[:] = 1
    s += dff[c].value_counts()
    s.fillna(1, inplace=True)
    return s.astype('int64')

In [82]:
for c in dfn.columns:
    print(smooth(df, dfn, 'outlook'))
    print('-' * 30)

sunny       4
rainy       3
overcast    1
Name: outlook, dtype: int64
------------------------------
sunny       4
rainy       3
overcast    1
Name: outlook, dtype: int64
------------------------------
sunny       4
rainy       3
overcast    1
Name: outlook, dtype: int64
------------------------------
sunny       4
rainy       3
overcast    1
Name: outlook, dtype: int64
------------------------------
sunny       4
rainy       3
overcast    1
Name: outlook, dtype: int64
------------------------------


In [81]:
for c in dfy.columns:
    print(smooth(df, dfy, 'outlook'))
    print('-' * 30)

sunny       3
rainy       4
overcast    3
Name: outlook, dtype: int64
------------------------------
sunny       3
rainy       4
overcast    3
Name: outlook, dtype: int64
------------------------------
sunny       3
rainy       4
overcast    3
Name: outlook, dtype: int64
------------------------------
sunny       3
rainy       4
overcast    3
Name: outlook, dtype: int64
------------------------------
sunny       3
rainy       4
overcast    3
Name: outlook, dtype: int64
------------------------------


# sk learn

In [87]:
    import numpy as np
    X = np.array([1, 1, 1, 0, 0, 1, 1])
    X = X.reshape(-1,1)
    y = np.array([0, 0, 0, 0, 1, 1, 1])

    from sklearn.naive_bayes import MultinomialNB
    clf = MultinomialNB()
    clf.fit(X, y)

    print(clf.predict(X))
    print(clf.predict_proba(X))
    
    [0 0 0 0 0 0 0]
    [[0.57142857 0.42857143]
     [0.57142857 0.42857143]
     [0.57142857 0.42857143]
     [0.57142857 0.42857143]
     [0.57142857 0.42857143]
     [0.57142857 0.42857143]
     [0.57142857 0.42857143]]

[0 0 0 0 0 0 0]
[[0.57142857 0.42857143]
 [0.57142857 0.42857143]
 [0.57142857 0.42857143]
 [0.57142857 0.42857143]
 [0.57142857 0.42857143]
 [0.57142857 0.42857143]
 [0.57142857 0.42857143]]


In [ ]:
from sklearn.preprocessing import LabelEncoder

X = df.apply(LabelEncoder().fit_transform)
y = LabelEncoder().fit_transform(df.play)
X

In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X, y)

In [ ]:
nb.predict(X)

In [ ]:
y == nb.predict(X)

In [ ]:
nb.predict_proba(X)

In [ ]:
X = df.apply(LabelEncoder().fit_transform)
y = LabelEncoder().fit_transform(df.play)
X

In [ ]:
X

In [ ]:
nb.class_count_

# Learn with 1 attribute

In [ ]:
X = LabelEncoder().fit_transform(df.temperature)
X = X.reshape(-1,1)

In [ ]:
nb.fit(X,y)
nb.predict(X)

In [ ]:
nb.predict_proba(X)