In [0]:
import numpy as np

# การสร้าง array 1D

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(2, 10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.arange(2, 10, 2.5)
a

array([2. , 4.5, 7. , 9.5])

In [6]:
a = np.linspace(2, 10, 17)
a

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [7]:
a.shape

(17,)

In [8]:
type(a.shape)

tuple

In [9]:
np.random.rand(3)

array([0.12191473, 0.980079  , 0.97111697])

In [10]:
np.random.randint(1, 7, 5)   # toss a die 5 times

array([2, 4, 1, 4, 6])

In [35]:
a = np.concatenate(([1,2,3], [4,5,6]))
a

array([1, 2, 3, 4, 5, 6])

# สร้างอาร์เรย์ 2D

In [11]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
m.shape

(2, 3)

In [13]:
a = [1,2,3]
b = [4,5,6]
m = np.column_stack((a,b))
m

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
np.random.rand(2, 3)

array([[0.44157347, 0.46513496, 0.28693772],
       [0.87750327, 0.55951057, 0.5612898 ]])

# Calculation

In [0]:
a = np.array([2,1,6])
b = np.array([9,2,6])

In [16]:
a + b

array([11,  3, 12])

In [17]:
np.dot(a, b) == 2*9 + 1*2 + 6*6

True

In [18]:
a.sum()   # mean std max min

9

In [19]:
a == b

array([False, False,  True])

In [20]:
np.any(a==b)

True

In [21]:
np.all(a==b)

False

# Reshape

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a = a.reshape(4,-1)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
a = a.reshape(-1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
a = a.reshape(2,-1)
a = a.transpose()
a

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])